<template>
  <div class="paper-page" v-loading="loading">
    <el-alert title="线上模拟交易：使用实时行情计算，资金、持仓和成交记录按登录账户保存；不连接真实交易所。" type="warning" :closable="false" show-icon />
    <el-row :gutter="16" class="summary">
      <el-col :span="8"><el-card><div>账户权益</div><b>¥ {{ money(account.equity) }}</b></el-card></el-col>
      <el-col :span="8"><el-card><div>可用资金</div><b>¥ {{ money(account.cash) }}</b></el-card></el-col>
      <el-col :span="8"><el-card><div>浮动盈亏</div><b :class="account.unrealizedPnl >= 0 ? 'rise' : 'fall'">{{ signed(account.unrealizedPnl) }}</b></el-card></el-col>
    </el-row>
    <el-card class="trade"><template #header>闪电下单</template><el-select v-model="form.contractCode" filterable placeholder="选择实时合约" style="width:320px"><el-option v-for="item in quotes" :key="item.contractCode" :label="`${item.contractName} ${item.contractCode}`" :value="item.contractCode" /></el-select><el-button type="primary" class="lightning-button" @click="drawer = true">闪电下单</el-button></el-card>
    <el-drawer v-model="drawer" direction="btt" size="28%" title="闪电下单"><div class="lightning-panel"><b>{{ selectedQuote?.contractName }} {{ selectedQuote?.contractCode }}</b><span>1 手保证金 ¥ {{ money(oneMargin) }}</span><div class="quick-line"><el-button>−</el-button><b>对手价 {{ price(selectedQuote?.lastPx) }}</b><el-button>＋</el-button><el-input-number v-model="form.quantity" :min="1" :max="Math.max(1, maxLots)" /><b>{{ form.quantity }} 手</b></div><div class="limits"><span>跌停 {{ price(selectedQuote?.downPx) }}</span><span>价格 {{ price(selectedQuote?.lastPx) }}</span><span>涨停 {{ price(selectedQuote?.upPx) }}</span><span>最多 {{ maxLots }} 手</span></div><div class="lightning-actions"><el-button type="danger" @click="open('多')">加多</el-button><el-button type="success" :disabled="!selectedPositions.length" @click="lock">锁单</el-button><el-button type="primary" :disabled="!selectedPositions.length" @click="closeCurrent">平仓</el-button></div></div></el-drawer>
    <el-card class="table"><template #header>当前持仓</template><el-table :data="account.positions" empty-text="暂无持仓，提交模拟订单后在此查看"><el-table-column prop="contractName" label="合约" /><el-table-column prop="side" label="方向"><template #default="{ row }"><span :class="row.side === '多' ? 'rise' : 'fall'">{{ row.side }}</span></template></el-table-column><el-table-column prop="quantity" label="手数" /><el-table-column label="均价 / 最新"><template #default="{ row }">{{ price(row.averagePrice) }} / {{ price(row.lastPrice) }}</template></el-table-column><el-table-column label="浮动盈亏"><template #default="{ row }"><span :class="row.unrealizedPnl >= 0 ? 'rise' : 'fall'">{{ signed(row.unrealizedPnl) }}</span></template></el-table-column><el-table-column label="操作" width="100"><template #default="{ row }"><el-button link type="danger" @click="close(row.positionId)">平仓</el-button></template></el-table-column></el-table></el-card>
    <el-card class="table"><template #header>最近成交</template><el-table :data="orders" empty-text="暂无成交记录"><el-table-column prop="createTime" label="时间" min-width="165" /><el-table-column prop="contractName" label="合约" /><el-table-column label="操作"><template #default="{ row }">{{ row.action }}{{ row.side }}</template></el-table-column><el-table-column prop="quantity" label="手数" /><el-table-column label="成交价"><template #default="{ row }">{{ price(row.price) }}</template></el-table-column><el-table-column label="已实现盈亏"><template #default="{ row }"><span v-if="row.realizedPnl !== null" :class="row.realizedPnl >= 0 ? 'rise' : 'fall'">{{ signed(row.realizedPnl) }}</span><span v-else>—</span></template></el-table-column></el-table></el-card>
  </div>
</template>
<script setup name="FuturePaperTrading">
import { computed, reactive, ref } from 'vue'
import { listFutureQuote } from '@/api/future/market'
import { closePaperPosition, getPaperAccount, openPaperPosition } from '@/api/future/paper-trading'
const loading = ref(false); const drawer = ref(false); const quotes = ref([]); const orders = ref([]); const account = reactive({ cash: 0, equity: 0, unrealizedPnl: 0, positions: [] }); const form = reactive({ contractCode: '', side: '多', quantity: 1 }); const selectedQuote = computed(() => quotes.value.find(item => item.contractCode === form.contractCode)); const oneMargin = computed(() => (selectedQuote.value?.lastPx || 0) * (selectedQuote.value?.contractUnit || 1)); const maxLots = computed(() => Math.floor(account.cash / (oneMargin.value || 1))); const selectedPositions = computed(() => account.positions.filter(item => item.contractCode === form.contractCode))
const money = value => Number(value || 0).toFixed(2); const price = money; const signed = value => `${Number(value || 0) >= 0 ? '+' : ''}${money(value)}`
async function load() { loading.value = true; try { const [accountRes, quoteRes, orderRes] = await Promise.all([getPaperAccount(), listFutureQuote({ scope: 'domestic', pageNum: 1, pageSize: 100 }), getPaperOrders()]); Object.assign(account, accountRes.data); quotes.value = quoteRes.data.rows || []; orders.value = orderRes.data || []; if (!form.contractCode) form.contractCode = quotes.value[0]?.contractCode || '' } finally { loading.value = false } }
async function open(side) { if (!form.contractCode) return ElMessage.warning('请选择合约'); await ElMessageBox.confirm(`${selectedQuote.value.contractName} ${side === '多' ? '加多' : '锁单'} ${form.quantity} 手，保证金 ¥${money(oneMargin.value * form.quantity)}`, '确认闪电下单'); await openPaperPosition({ ...form, side }); drawer.value = false; ElMessage.success('模拟开仓成功'); load() }
async function lock() { const position = selectedPositions.value[0]; if (position) await open(position.side === '多' ? '空' : '多') }
async function closeCurrent() { for (const position of selectedPositions.value) await close(position.positionId); drawer.value = false }
async function close(positionId) { await closePaperPosition(positionId); ElMessage.success('已模拟平仓'); load() }
load()
</script>
<style scoped>.paper-page{padding:20px}.summary{margin:16px 0}.summary b{display:block;font-size:25px;margin-top:10px}.trade,.table{margin-top:16px}.lightning-button{margin-left:12px}.lightning-panel{max-width:760px;margin:auto;display:grid;gap:16px}.quick-line,.limits,.lightning-actions{display:flex;align-items:center;gap:12px}.quick-line{font-size:18px}.quick-line .el-input-number{margin-left:auto}.limits{justify-content:space-between;color:#7b8794;font-size:13px}.lightning-actions .el-button{flex:1}.rise{color:#f56c6c}.fall{color:#67c23a}</style>
