<template>
  <view class="page"><view class="content">
    <view class="progress"><text>第 {{ index + 1 }} / {{ words.length }} 个单词</text><view class="bar"><view :style="{ width: ((index + 1) / words.length * 100) + '%' }"></view></view></view>
    <view v-if="current" class="word-card" @click="speak"><iframe v-if="current.animation" class="scene" :src="current.animation.url"></iframe><view class="word-info"><text class="word">{{ current.word }}</text><text class="sound">🔊 点我听英音</text><text class="meaning">{{ current.meaning_zh }}</text></view></view>
    <view v-if="current" class="example"><text class="example-title">跟着读</text><text>{{ current.example_en }}</text><text>{{ current.example_zh }}</text></view>
    <view class="actions"><button class="known" @click="next">我会啦 ✓</button><button class="next" @click="next">下一个 →</button></view>
  </view></view>
</template>
<script>
import { firstUnitWords } from '@/common/english-api'
export default { data() { return { words: [], index: 0, player: null } }, computed: { current() { return this.words[this.index] } }, async onLoad() { try { this.words = await firstUnitWords() } catch { uni.showToast({ title: '课本加载失败', icon: 'none' }) } }, methods: { speak() { const url = this.current && this.current.audio && (this.current.audio.uk || this.current.audio.us); if (!url) return; this.player = uni.createInnerAudioContext(); this.player.src = url; this.player.play() }, next() { if (this.index < this.words.length - 1) this.index++; else { uni.showToast({ title: '真棒！学完啦', icon: 'success' }); this.addStar() } }, addStar() { const p = uni.getStorageSync('englishGarden_progress') || { stars: 0, streak: 1, correct: 0 }; p.stars = (p.stars || 0) + 1; uni.setStorageSync('englishGarden_progress', p) } } }
</script>
<style lang="scss" scoped>
.page { min-height:100vh;padding:45rpx 0;background:#fff9ed }.content { width:82%;max-width:900px;margin:auto }.progress { font-size:26rpx;color:#777 }.bar { height:16rpx;margin-top:16rpx;background:#f0dfca;border-radius:10rpx;overflow:hidden }.bar view { height:100%;background:#ff9b55 }.word-card {position:relative;min-height:500rpx;margin-top:44rpx;overflow:hidden;text-align:center;border-radius:36rpx;background:#fff;box-shadow:0 12rpx 30rpx rgba(86,55,15,.12)}.scene{position:absolute;inset:0;width:100%;height:100%;border:0;pointer-events:none;z-index:0}.word-info{position:absolute;z-index:1;left:0;right:0;bottom:0;padding:20rpx 30rpx 34rpx;background:linear-gradient(transparent,rgba(255,255,255,.94) 35%)}.word{display:block;margin-top:20rpx;font-size:68rpx;font-weight:800;color:#ff7c55}.sound{display:block;margin-top:18rpx;font-size:27rpx;color:#778}.meaning{display:block;margin-top:24rpx;font-size:34rpx;font-weight:700}.example{margin-top:30rpx;background:#fff0d9;padding:27rpx 34rpx;border-radius:24rpx;font-size:30rpx}.example-title{font-weight:800;margin-right:22rpx}.actions{margin-top:38rpx;display:flex;gap:25rpx}.actions button{flex:1;font-size:31rpx;border-radius:52rpx}.known{color:#4a9c61;background:#e0f6e4}.next{color:white;background:#ff805b}
</style>
